name: flutter_file_adapter
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/shaozict

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.0
  test: ^1.16.3